/*
   요구사항
   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
   음료수 당첨번호 / 당첨자 당첨 상품 / 배송중
*/
CREATE SEQUENCE SEQ_DRINK;
CREATE TABLE TBL_DRINK(
	ID NUMBER CONSTRAINT PK_DRINK PRIMARY KEY,
	WIN_NUMBER NUMBER NOT NULL UNIQUE
);
CREATE SEQUENCE SEQ_WINNER;
CREATE TABLE TBL_WINNER(
	ID NUMBER CONSTRAINT PK_WINNER PRIMARY KEY,
	WINNER_NAME VARCHAR2(255),
	WINNDER_ADDRESS VARCHAR2(255),
	DRINK_ID NUMBER,
	CONSTRAINT FK_WINNER_DRINK FOREIGN KEY(DRINK_ID)
	REFERENCES TBL_DRINK(WIN_NUMBER)
);
CREATE TABLE TBL_PRISE(
	ID NUMBER CONSTRAINT PK_PRISE PRIMARY KEY,
	PRISE_GOODS VARCHAR2(255),
	WINNER_ID NUMBER,
	CONSTRAINT FK_PRISE_WINNER FOREIGN KEY(WINNER_ID)
	REFERENCES TBL_WINNER(ID)
);
CREATE TABLE TBL_DELIVERY(
	ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
	DELIVERY_STATE VARCHAR(255),
	PRISE_ID NUMBER,
	CONSTRAINT FK_DELIVERY_PRISE FOREIGN KEY(PRISE_ID)
	REFERENCES TBL_PRISE(ID)
);

/*
요구사항
   이커머스 창업 준비중입니다. 
   기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
   기업의 정보는 기업 이름, 주소, 대표번호가 있고
   사용자 정보는 이름, 주소, 전화번호가 있습니다.
   상품의 정보는 이름, 가격, 재고입니다.
   카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
   
   결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보, 상품의 정보가 필요합니다. 
   사용자는 등록한 카드의 정보를 저장할 수 있다. 
*/
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255),
	COMAPNY_ADDRESS VARCHAR2(255),
	COMPANY_PHONE VARCHAR2(255)
);
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_ADDRESS VARCHAR2(255),
	USER_PHONE VARCHAR2(255)
);
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255),
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 0
);
CREATE SEQUENCE SEQ_CARD;
CREATE TABLE TBL_CARD(
	ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
	CARD_NUMBER NUMBER NOT NULL UNIQUE,
	CARD_COMPANY VARCHAR2(255),
	CARD_USER VARCHAR2(255),
	USER_ID NUMBER,
	CONSTRAINT FK_CARD_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);
CREATE TABLE PURCHASE(
	ID NUMBER CONSTRAINT PK_PURCHASE PRIMARY KEY,
	COMPANY_ID NUMBER,
	USER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CARD_ID NUMBER,
	CONSTRAINT FK_PURCHASE_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_PURCHASE_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID),
	CONSTRAINT FK_PURCHASE_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID),
	CONSTRAINT FK_PURCHASE_CARD FOREIGN KEY(CARD_ID)
	REFERENCES TBL_CARD(ID)
);